In [17]:
import pandas as pd
import numpy as np
import sklearn.model_selection
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error
import sklearn.preprocessing

In [18]:
# running locally, do not use Colab-specific drive mount
# use a local file path for the dataset in the next cell instead
# running locally, do not use Colab-specific drive mount
# use a local file path for the dataset in the next cell instead

In [19]:
import os

# look for the dataset in common local locations instead of Colab drive
for path in ("LungCapData2.csv", "./LungCapData2.csv", "data/LungCapData2.csv"):
    if os.path.exists(path):
        data = pd.read_csv(path)
        break
else:
    raise FileNotFoundError("LungCapData2.csv not found. Place the file in the notebook directory or update the path.")
data

     Age  LungCap  Height  Gender Smoke
0      9    3.124    57.0  female    no
1      8    3.172    67.5  female    no
2      7    3.160    54.5  female    no
3      9    2.674    53.0    male    no
4      9    3.685    57.0    male    no
..   ...      ...     ...     ...   ...
649   16   10.810    67.0    male   yes
650   15    9.181    68.0    male   yes
651   18    6.559    60.0  female    no
652   16    6.385    63.0  female   yes
653   15    7.633    66.5  female    no

[654 rows x 5 columns]

In [20]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 654 entries, 0 to 653
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Age      654 non-null    int64
 1   LungCap  654 non-null    float64
 2   Height   654 non-null    float64
 3   Gender   654 non-null    str
 4   Smoke    654 non-null    str
dtypes: float64(2), int64(1), str(2)
memory usage: 30.2 KB

In [21]:
data.isnull().sum()

Age        0
LungCap    0
Height     0
Gender     0
Smoke      0
dtype: int64

In [22]:
data[data.duplicated()]

     Age  LungCap  Height  Gender Smoke
264    8    5.893    59.0    male    no
491   10    4.750    58.0  female    no
505   13    7.891    65.0  female   yes

In [23]:
data.drop_duplicates(inplace=True)

In [24]:
data[data.duplicated()]

Empty DataFrame
Columns: [Age, LungCap, Height, Gender, Smoke]
Index: []

In [25]:
X = data.drop("LungCap", axis=1)
y = data["LungCap"]

In [26]:
X.columns

Index(['Age', 'Height', 'Gender', 'Smoke'], dtype='str')

In [27]:
print(X.columns)

Index(['Age', 'Height', 'Gender', 'Smoke'], dtype='str')

In [28]:
data.info()

<class 'pandas.DataFrame'>
Index: 651 entries, 0 to 653
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Age      651 non-null    int64
 1   LungCap  651 non-null    float64
 2   Height   651 non-null    float64
 3   Gender   651 non-null    str
 4   Smoke    651 non-null    str
dtypes: float64(2), int64(1), str(2)
memory usage: 35.2 KB

In [29]:
data["Gender"]=data["Gender"].map({"Male":1,"Female":0,"male":1,"female":0})

In [30]:
data["Smoke"]=data["Smoke"].map({"Yes":1,"No":0,"yes":1,"no":0})

In [31]:
data.info()

<class 'pandas.DataFrame'>
Index: 651 entries, 0 to 653
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Age      651 non-null    int64
 1   LungCap  651 non-null    float64
 2   Height   651 non-null    float64
 3   Gender   651 non-null    int64
 4   Smoke    651 non-null    int64
dtypes: float64(2), int64(3)
memory usage: 30.5 KB

In [32]:
print(data)

     Age  LungCap  Height  Gender  Smoke
0      9    3.124    57.0       0      0
1      8    3.172    67.5       0      0
2      7    3.160    54.5       0      0
3      9    2.674    53.0       1      0
4      9    3.685    57.0       1      0
..   ...      ...     ...     ...    ...
649   16   10.810    67.0       1      1
650   15    9.181    68.0       1      1
651   18    6.559    60.0       0      0
652   16    6.385    63.0       0      1
653   15    7.633    66.5       0      0

[651 rows x 5 columns]

In [33]:
data

     Age  LungCap  Height  Gender  Smoke
0      9    3.124    57.0       0      0
1      8    3.172    67.5       0      0
2      7    3.160    54.5       0      0
3      9    2.674    53.0       1      0
4      9    3.685    57.0       1      0
..   ...      ...     ...     ...    ...
649   16   10.810    67.0       1      1
650   15    9.181    68.0       1      1
651   18    6.559    60.0       0      0
652   16    6.385    63.0       0      1
653   15    7.633    66.5       0      0

[651 rows x 5 columns]

In [34]:
if 'data' not in globals():
    data = pd.read_csv('LungCapData2.csv')

X = data.drop("LungCap", axis=1)
y = data["LungCap"]

X_train, X_test, y_train, y_test = sklearn.model_selection.train_test_split(
    X, y, test_size=0.2, random_state=42
)
y = data["LungCap"]

X_train, X_test, y_train, y_test = sklearn.model_selection.train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [35]:
print(X_train.shape)
print(X_test.shape)

(520, 4)
(131, 4)

In [36]:
from sklearn.preprocessing import OneHotEncoder

X = pd.get_dummies(X, drop_first=True)

In [37]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
# Encode categorical variables
X = pd.get_dummies(X, drop_first=True)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
X_test_scaled = scaler.transform(X_test)

In [38]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X_train_scaled,y_train)

LinearRegression()

In [39]:
y_pred_train=model.predict(X_train_scaled)
y_pred_test=model.predict(X_test_scaled)

In [40]:
print("-------------------------------------------------------")
print("Training Result:")
print("-------------------------------------------------------")
print("RMSE:",np.sqrt(mean_squared_error(y_train,y_pred_train)))
print("MAE:",mean_absolute_error(y_train,y_pred_train))
print("R2 Score:",r2_score(y_train,y_pred_train))
print("-------------------------------------------------------")
print("Testing Result:")
print("-------------------------------------------------------")
print("RMSE:",np.sqrt(mean_squared_error(y_test,y_pred_test)))
print("MAE:",mean_absolute_error(y_test,y_pred_test))
print("R2 Score:",r2_score(y_test,y_pred_test))
print("-------------------------------------------------------")

-------------------------------------------------------
Training Result:
-------------------------------------------------------
RMSE: 1.1782954012743705
MAE: 0.9115988439686581
R2 Score: 0.777813393047762
-------------------------------------------------------
Testing Result:
-------------------------------------------------------
RMSE: 1.441912269724026
MAE: 1.051159097082926
R2 Score: 0.7659411970353404
-------------------------------------------------------

In [41]:
modelRidge=Ridge()
modelRidge.fit(X_train_scaled,y_train)

Ridge()

In [42]:
y_pred_train=modelRidge.predict(X_train_scaled)
y_pred_test=modelRidge.predict(X_test_scaled)

In [43]:
print("-------------------------------------------------------")
print("Training Result:")
print("-------------------------------------------------------")
print("RMSE:",np.sqrt(mean_squared_error(y_train,y_pred_train)))
print("MAE:",mean_absolute_error(y_train,y_pred_train))
print("R2 Score:",r2_score(y_train,y_pred_train))
print("-------------------------------------------------------")
print("Testing Result:")
print("-------------------------------------------------------")
print("RMSE:",np.sqrt(mean_squared_error(y_test,y_pred_test)))
print("MAE:",mean_absolute_error(y_test,y_pred_test))
print("R2 Score:",r2_score(y_test,y_pred_test))
print("-------------------------------------------------------")

-------------------------------------------------------
Training Result:
-------------------------------------------------------
RMSE: 1.1783027241758899
MAE: 0.9116564552649531
R2 Score: 0.7778106313367416
-------------------------------------------------------
Testing Result:
-------------------------------------------------------
RMSE: 1.442240599945558
MAE: 1.0508984181119856
R2 Score: 0.7658345923137709
-------------------------------------------------------

In [44]:
feature_importance=pd.DataFrame({
    "Feature": X.columns,
    "Coefficient":modelRidge.coef_
})
feature_importance.sort_values(by="Coefficient",ascending=False)
feature_importance

  Feature  Coefficient
0     Age     0.565118
1  Height     1.720587
2  Gender     0.219295
3   Smoke    -0.082988

In [45]:
comparison=pd.DataFrame({
    "Actual":y_test,
    "Predicted":y_pred_test
})
comparison.head(10)

     Actual  Predicted
641  10.897   8.764562
265   5.650   3.946455
259   4.168   3.330967
497   6.031   7.774416
72    6.145   5.564246
441  11.779   8.720756
250   2.029   2.083430
131   2.287   4.601478
328   5.995   6.435651
279   2.077   1.867048

In [46]:
from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV
param_grid = {
    'alpha': [0.001,0.01,0.1,1,10]
}
grid = GridSearchCV(
    estimator=Ridge(),
    param_grid=param_grid,
    cv=5,
    scoring='r2'
)
grid.fit(X_train_scaled, y_train)
print("Best Alpha:", grid.best_params_)
print("Best Score:", grid.best_score_)

Best Alpha: {'alpha': 1}
Best Score: 0.765511627391912

In [47]:
new_data = [[16,57,1, 0]]

predicted_result = modelRidge.predict(new_data)

print("Predicted Result:", predicted_result[0])

Predicted Result: 113.24074077704188

In [48]:
import pickle

In [49]:
with open('model.pkl', 'wb') as file:
    pickle.dump(modelRidge, file)

In [50]:
with open('model.pkl', 'rb') as file:
    mp = pickle.load(file)

In [51]:
mp.predict(new_data)

array([113.24074078])

In [52]:
import pickle

with open("model.pkl", "wb") as f:
    # choose the trained model to save (prefer grid best_estimator_ if available)
    if 'grid' in globals() and hasattr(grid, 'best_estimator_'):
        model_to_save = grid.best_estimator_
    elif 'modelRidge' in globals():
        model_to_save = modelRidge
    elif 'model' in globals():
        model_to_save = model
    else:
        raise NameError("No trained model found. Run the training cells first.")
        
        pickle.dump(model_to_save, f)       

    with open("scaler.pkl", "wb") as f:
        pickle.dump(scaler, f)

    with open("model.pkl", "wb") as f:
        pickle.dump(model_to_save, f)